CREATE TABLE IF NOT EXISTS chats (
  id         VARCHAR(64) NOT NULL PRIMARY KEY,
  persona    VARCHAR(64) NOT NULL DEFAULT 'magi-core',
  title      VARCHAR(255) NOT NULL DEFAULT 'New Chat',
  pinned     TINYINT(1) NOT NULL DEFAULT 0,
  working_dir VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
  id         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  chat_id    VARCHAR(64) NOT NULL,
  role       VARCHAR(32) NOT NULL,
  content    LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS message_embeddings (
  message_id BIGINT NOT NULL PRIMARY KEY,
  embedding  LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);
